### PR TITLE
Implementation of 10Gig downloads

### PR DESCRIPTION
**Pull request by 8ryn**
This implements downloads over the 10 gig link. It works well for P10 downloads of < 1677 frames.

I have created some follow up tickets to achieve the following:

- Solve issue of final frame not loading for downloads > 1677 frames
-  Solve dropped frames in P12L format downloads
- Set the pcap buffer appropriately and automatically download in appropriate sized chunks based on that
- Customise the device you are connecting to in the constructor rather than the hardcoded "p1p1" connection currently
- Implement appropriate abort behaviour for the 10 gig downloads

I would suggest waiting for most of these to be resolved before actually merging.

### CODE REVIEW

**Comment by 8ryn** [comment]
Serious issue with final frame has been solved by splitting download into 2GB chunks inline with manufacturer instructions. P12L download issue also solved.

Only remaining issues are implementing appropriate abort behaviour and updating the example IOC/xml.

**Comment by 8ryn** [comment]
All remaining issues I can see have now been resolved so this is now ready for review.

**Review by ptsOSL — COMMENTED** [review]
Looks good to me. It would be nice to have a parameter which tracks the number of missing packets and displays this in EDM, but this can be done in another merge request if you prefer.

**Comment by 8ryn** [comment]
Thanks a lot! Yes I'll probably add that change prior to merging

**Pull request merged**
